catalog/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.index, name='index'),
    path('books/', views.BookListView.as_view(), name='books'),
    path('book/<int:pk>', views.BookDetailView.as_view(), name="book-detail"),
    path('authors/', views.AuthorListView.as_view(), name='authors'),
    path('author/<int:pk>', views.AuthorDetailView.as_view(), name="author-detail"),
    path('mybooks/', views.LoanedBooksByUserListView.as_view(), name="my-borrowed"),
    path('borrowed/', views.LoanedBooksAllUsersListView.as_view(), name="all-borrowed"),
    path('book/<uuid:pk>/renew/', views.renew_book_librarian,
         name="renew-book-librarian"),
    path('author/create/', views.AuthorCreate.as_view(), name='author_create'),
    path('author/<int:pk>/update/',
         views.AuthorUpdate.as_view(), name="author_update"),
    path('author/<int:pk>/delete/',
         views.AuthorDelete.as_view(), name='author_delete'),

    path('book/create/', views.BookCreate.as_view(), name='book_create'),
    path('book/<int:pk>/update/',
         views.BookUpdate.as_view(), name="book_update"),
    path('book/<int:pk>/delete/',
         views.BookDelete.as_view(), name='book_delete')
]

locallibrary/urls.py
from django.contrib import admin
from django.urls import path
from django.urls import include
from django.views.generic import RedirectView
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
]

urlpatterns += [
    path('catalog/', include('catalog.urls')),
]

urlpatterns += [
    path('', RedirectView.as_view(url='catalog/', permanent=True))
]

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

urlpatterns += [
    path("accounts/", include("django.contrib.auth.urls")),
]

catalog/models.py
from django.db import models
from django.contrib.auth.models import User
from django.urls import reverse
import uuid
from datetime import date

# Create your models here.

# Genre model


class Genre(models.Model):
    """Model representing a book genre."""
    name = models.CharField(
        max_length=200, help_text="Enter a book genre(e.g Science Fiction)")

    def __str__(self):
        """String for representing the Model object."""
        return self.name

# Book model


class Book(models.Model):
    url = "https://www.isbn-international.org/content/what-isbn"
    title = models.CharField(max_length=200)
    #
    # Foreign Key used because book can only have one author, but authors can have multiple books
    # Author as a string rather than object because it hasn't been declared yet in the file
    #
    author = models.ForeignKey('Author', on_delete=models.SET_NULL, null=True)
    summary = models.TextField(
        max_length=1000, help_text="Enter a brief description of the book")
    isbn = models.CharField("ISBN", max_length=13,
                            help_text="13 Character <a href="f'{url}'">ISBN number</a>'")

    #
    # ManyToManyField used because genre can contain many books. Books can cover many genres.
    # Genre class has already been defined so we can specify the object above.
    #
    genre = models.ManyToManyField(
        Genre, help_text="Select a genre for this book")

    language = models.ForeignKey(
        'Language', on_delete=models.SET_NULL, null=True)

    def display_genre(self):
        """Create a string for the Genre. This is required to display genre in Admin."""
        return ', '.join(genre.name for genre in self.genre.all()[:3])

    display_genre.short_description = 'Genre'

    def get_absolute_url(self):
        return reverse('book-detail', args=[str(self.id)])

    def __str__(self):
        return self.title


class BookInstance(models.Model):
    id = models.UUIDField(primary_key=True, default=uuid.uuid4,
                          help_text="Unique ID for this particular book across whole library")
    book = models.ForeignKey('Book', on_delete=models.SET_NULL, null=True)
    imprint = models.CharField(max_length=200)
    due_back = models.DateField(null=True, blank=True)
    LOAN_STATUS = (('m', 'Maintenance'),
                   ('o', 'On loan'),
                   ('a', 'Available'),
                   ('r', 'Reserved'),
                   )

    status = models.CharField(max_length=1, choices=LOAN_STATUS,
                              blank=True, default='m', help_text='Book availability')
    borrower = models.ForeignKey(
        User, on_delete=models.SET_NULL, null=True, blank=True)

    class Meta:
        ordering = ['due_back']
        permissions = (("can_mark_returned", "Set book as returned"),)

    def __str__(self):
        return f'{self.id} ({self.book.title})'

    # Check if a bookinstance is overdue
    @property
    def is_overdue(self):
        if self.due_back and date.today() > self.due_back:
            return True
        return False


class Author(models.Model):
    first_name = models.CharField(max_length=100)
    last_name = models.CharField(max_length=100)
    date_of_birth = models.DateField(null=True, blank=True)
    date_of_death = models.DateField('died', null=True, blank=True)

    class Meta:
        ordering = ['last_name', 'first_name']

    def get_absolute_url(self):
        return reverse('author-detail', args=[str(self.id)])

    def __str__(self):
        return f'{self.last_name}, {self.first_name}'


class Language(models.Model):
    name = models.CharField(
        max_length=200, help_text="Enter the book's natural language(e.g English, French, Japanese etc..)")

    def __str__(self):
        return self.name

catalog/forms.py
import datetime
from django import forms
from django.core.exceptions import ValidationError
from django.utils.translation import ugettext_lazy as _


class RenewBookForm(forms.Form):
    renewal_date = forms.DateField(
        help_text="Enter a date between now and 4 weeks (default 3).")

    def clean_renewal_date(self):
        data = self.cleaned_data['renewal_date']
        if data < datetime.date.today():
            raise ValidationError(_('Indavid date - renewal in past'))

        if data > datetime.date.today() + datetime.timedelta(weeks=4):
            raise ValidationError(
                _('Indavid date - renewal more than 4 weeks ahead'))

        return data

catalog/views.py
import datetime
from django.shortcuts import render, get_object_or_404
from django.http import HttpResponseRedirect
from django.urls import reverse, reverse_lazy
from django.views import generic
from catalog.models import Book, Author, BookInstance, Genre
from catalog.forms import RenewBookForm
from django.contrib.auth.mixins import LoginRequiredMixin, PermissionRequiredMixin
from django.contrib.auth.decorators import permission_required
from django.views.generic.edit import CreateView, UpdateView, DeleteView
# Create your views here.


def index(request):
    """View function for home page of site"""
    # Generate counts of some of the main objects

    num_books = Book.objects.all().count()
    num_instances = BookInstance.objects.all().count()

    # Available book (status = "a")
    num_instances_available = BookInstance.objects.filter(
        status__exact="a").count()

    # The all() is impled by default
    num_authors = Author.objects.count()

    # find all the novels, genre__name icontains "novel" (case insensitive)
    num_novels = Book.objects.filter(genre__name__icontains="novel").count()

    num_harrypotters = Book.objects.filter(
        title__icontains="harry potter").count()

    num_visits = request.session.get('num_visits', 0)
    request.session['num_visits'] = num_visits + 1

    context = {
        'num_books': num_books,
        'num_instances': num_instances,
        'num_instances_available': num_instances_available,
        'num_authors': num_authors,
        'num_novels': num_novels,
        'num_harrypotters': num_harrypotters,
        'num_visits': num_visits,

    }

    # Render the HTML template index.html with the date in the context variable
    return render(request, 'index.html', context=context)


class BookListView(generic.ListView):
    model = Book
    paginate_by = 10


class BookDetailView(generic.DetailView):
    model = Book


class AuthorListView(generic.ListView):
    model = Author
    paginate_by = 10


class AuthorDetailView(generic.DetailView):
    model = Author


class LoanedBooksByUserListView(LoginRequiredMixin, generic.ListView):
    """Generic class-based view listing books on loan to current user."""
    model = BookInstance
    template_name = "catalog/bookinstance_list_borrowed_user.html"
    paginate_by = 10

    def get_queryset(self):
        return BookInstance.objects.filter(borrower=self.request.user).filter(status__exact="o").order_by('due_back')


class LoanedBooksAllUsersListView(PermissionRequiredMixin, generic.ListView):
    permission_required = 'catalog.can_mark_returned'
    model = BookInstance
    template_name = "catalog/bookinstance_list_borrowed_all_user.html"
    paginate_by = 10

    def get_queryset(self):
        return BookInstance.objects.all().filter(status__exact="o").order_by('due_back')


@permission_required('catalog.can_mark_returned')
def renew_book_librarian(request, pk):
    book_instance = get_object_or_404(BookInstance, pk=pk)
    if request.method == 'POST':
        #
        # Create a form instance and populate it with data from the request (binding):
        #
        form = RenewBookForm(request.POST)
        if form.is_valid():
            book_instance.due_back = form.cleaned_data['renewal_date']
            book_instance.save()
            return HttpResponseRedirect(reverse('all-borrowed'))

    else:
        proposed_renewal_date = datetime.date.today() + datetime.timedelta(weeks=3)
        form = RenewBookForm(initial={'renewal_date': proposed_renewal_date})

    context = {
        'form': form,
        'book_instance': book_instance,
    }

    return render(request, 'catalog/book_renew_librarian.html', context)


class AuthorCreate(CreateView):
    model = Author
    fields = '__all__'
    initial = {'date_of_death': '05/01/2018'}


class AuthorUpdate(UpdateView):
    model = Author
    fields = ['first_name', 'last_name', 'date_of_death', 'date_of_death']


class AuthorDelete(DeleteView):
    model = Author
    success_url = reverse_lazy('authors')


class BookCreate(CreateView):
    model = Book
    fields = "__all__"


class BookUpdate(UpdateView):
    model = Book
    fields = "__all__"


class BookDelete(DeleteView):
    model = Book
    sucess_url = reverse_lazy('books')

catalog/templates/catalog/author_confirm_delete.html
{% extends "base_generic.html"%}
{% block content %}
<h1>Delete Author</h1>
<p>Are you sure you want to delete the author: {{author}}?</p>

<form action="" method="post">
	{% csrf_token %}
	<input type="submit" name="" value="Yes, delete.">
</form>
{% endblock %}

catalog/templates/catalog/author_detail.html
{% extends "base_generic.html" %}

{% block content %}
<h1>Author: {{author.last_name}} {{author.first_name}}</h1>

<p>
	{{author.date_of_birth}} - 
	{% if author.date_of_death %}
		{{author.date_of_death}}
	{% endif %}
</p>

<div class="book-detail">
	<h4>Books</h4>

	{% for book in author.book_set.all %}
		<hr>
		<p><a href="{% url 'book-detail' book.pk%}">{{book.title}}</a></p>
		<p>
			Total copies: ({{book.bookinstance_set.all.count}})
		</p>
		<h3>Summary:</h3>
		<p>{{book.summary}}</p>
	{% endfor %}
</div>
{% endblock %}

catalog/templates/catalog/author_form.html
{% extends "base_generic.html"%}
{% block content %}
	<form action="" method="post">
		{% csrf_token %}
		<table>
		{{ form.as_table }}
		</table>
		<input type="submit" value="Submit">
	</form>
{% endblock %}

catalog/templates/catalog/author_list.html
{%extends "base_generic.html" %}

{% block content %}
<h1>Author List</h1>
{% if author_list %}
<ul>
	{% for author in author_list %}
	<li>
		<a href="{{author.get_absolute_url}}">{{author.first_name}} {{author.last_name}}</a> 
		({{author.date_of_birth}} - 
		{% if author.date_of_death %}
			{{author.date_of_death}})
		{% else %}
			)
		{% endif %}
	</li>
	{% endfor %}
</ul>
{% else%}
	<p>There are no authors</p>
{% endif %}
{% endblock %}

catalog/templates/catalog/book_confirm_delete.html
{% extends "base_generic.html"%}
{% block content %}
<h1>Delete Author</h1>
<p>Are you sure you want to delete the author: {{author}}?</p>

<form action="" method="post">
	{% csrf_token %}
	<input type="submit" name="" value="Yes, delete.">
</form>
{% endblock %}

catalog/templates/catalog/book_detail.html
{% extends "base_generic.html" %}

{% block content %}
<h1>Title: {{book.title}}</h1>

<p><strong>Author:</strong><a href="{% url 'author-detail' book.author.pk %}">{{book.author}}</a></p>
<p><strong>Summary:</strong>{{book.summary}}</p>
<p><strong>ISBN:</strong>{{book.isbn}}</p>
<p><strong>Language:</strong>{{book.language}}</p>
<p><strong>Genre:</strong>{{book.genre.all|join:", "}}</p>

<div class="book-detail">
	<h4>Copies</h4>

	{% for copy in book.bookinstance_set.all %}
		<hr>
		<p class="{% if copy.status == 'a' %}text-success{% elif copy.status == 'm' %}text-danger{% else %}text-warning{% endif %}">
			{{ copy.get_status_display }}
		</p>
      {% if copy.status != 'a' %}
        <p><strong>Due to be returned:</strong> {{ copy.due_back }}</p>
      {% endif %}
      <p><strong>Imprint:</strong> {{ copy.imprint }}</p>
      <p class="text-muted"><strong>Id:</strong> {{ copy.id }}</p>
	{% endfor %}
</div>
{% endblock %}

catalog/templates/catalog/book_form.html
{% extends "base_generic.html"%}
{% block content %}
	<form action="" method="post">
		{% csrf_token %}
		<table>
		{{ form.as_table }}
		</table>
		<input type="submit" value="Submit">
	</form>
{% endblock %}

catalog/templates/catalog/book_list.html
{%extends "base_generic.html" %}

{% block content %}
<h1>Book List</h1>
{% if book_list %}
<ul>
	{% for book in book_list %}
	<li>
		<a href="{{book.get_absolute_url}}">{{book.title}}</a> ({{book.author}})
	</li>
	{% endfor %}
</ul>
{% else%}
	<p>There are no books in the library</p>
{% endif %}
{% endblock %}

catalog/templates/catalog/book_renew_librarian.html
{% extends "base_generic.html" %}

{% block content %}
	<h1>Renew: {{ book_instance.book.title }}</h1>
	<p>Borrower: {{ book_instance.borrower }}</p>
	<p {% if book_instance.is_overdue %} class="text-danger" {% endif %}>Due date: {{ book_instance.due_back }}</p>

	<form action="" method="post">
		{% csrf_token%}
		<table>
			{{ form.as_table}}
		</table>
		<input type="submit" name="" value="Submit">
	</form>
{% endblock %}

catalog/templates/catalog/bookinstance_list_borrowed_all_user.html
{% extends "base_generic.html"%}
{% block content %}
	<h1>Borrowed books</h1>
	{% if bookinstance_list%}
	<ul>
		{% for bookinst in bookinstance_list %}
		<li class="{% if bookinst.is_overdue %}text-danger{% endif %}">
			<a href="{% url 'book-detail' bookinst.book.pk %}">{{bookinst.book.title}}</a>({{ bookinst.due_back }}),Borrower :{{bookinst.borrower}}
		{% if perms.catalog.can_mark_returned and bookinst.is_overdue %}
		<a href="{% url 'renew-book-librarian' bookinst.id %}">Renew</a>  
		{% endif %}
		</li>
		{% endfor %}
	
	</ul>

	

	{% else %}
	<p>There are no books borrowed.</p>
	{% endif %}
{% endblock %}

catalog/templates/catalog/bookinstance_list_borrowed_user.html
{% extends "base_generic.html"%}
{% block content %}
	<h1>Borrowed books</h1>
	{% if bookinstance_list%}
	<ul>
		{% for bookinst in bookinstance_list %}
		<li class="{% if bookinst.is_overdue %}text-danger{% endif %}">
			<a href="{% url 'book-detail' bookinst.book.pk %}">{{bookinst.book.title}}</a>({{ bookinst.due_back }})
		</li>
		{% endfor %}
	</ul>

	{% else %}
	<p>There are no books borrowed.</p>
	{% endif %}
{% endblock %}